In [1]:
#define _FILE_SPECS "-rw-r--r-- 1 chris 8007 Mar 25 12:33 cartsim_data.py"
#define _MAGIC_NUMBER 1147484068
import numpy as np
import math, os,   sys,  time
from time import gmtime, strftime
# from logger import logger
from datetime import date, datetime, timezone
import statistics as st
import random as rn
import matplotlib.pyplot as plt
from numpy import random as rnn
 
from sklearn import metrics
import pickle

#equations
# M \ddot P = - C( X - X_0)  - D \dot X
#  P = X  + Z(Y(t))
#  Y(t)= vt

#  v=60km/hour = 16.666 m / sec
#
#  M= 1000kg
#  X_0 =  5cm
#  C spring const so 1000kg @ 10 m/sec^2 gives 5 cm ie
#    =   5 x 10e-06
#  X roughly +- 10cm
#  road 3 components period   1 sec, 2 sec, 4 sec (random amplitude)
#  sin(Y/(16.666)),  cos(Y/(16.666)), sin(Y/(2*16.66)), cos(Y/(2*16.66))
#  choose D0 to efold in 1 second ie. D/2M = 1.0 --> D=2000
#  too small is 'bad'
#  choose sampling rate @ 4 Hz
#  magnitude road = +- 5 max * sin( Y / 16.66 m)

#  10 minute samples = 600 x 4 points @ 4 Hz
#

def Zbase ( trigtype, period, K, Y):
    
    if trigtype=='sin':
        return math.sin( K * period * Y)
    if trigtype=='cos':
        return math.cos( K * period * Y)
    
def Zbaseddot ( trigtype, period, K, Y, v):
    
#     d^2/dt^ (VT)=0
    if trigtype=='sin':
        return -math.cos( K * period * Y) * v * v * (K /period) * (K/period)
    if trigtype=='cos':
        return -math.sin( K * period * Y) * v * v * (K /period) * (K/period)
    
def Xdot(Xn, Xnm1, dT):
    return (Xn - Xnm1)/dT

def Xddot(Xn, Xnm1, Xnm2, dT):
    return (Xn - 2 * Xnm1  + Xnm2)/(dT * dT)

def getXnp1(LHS, M, D, C, Xn, Xnm1, dT):
# solve for Xnp1
#  LHS = M(Xnp1 - 2 Xn + Xnm1)/delT^2 + D(Xnp1 - Xnm1)/2delT + C Xn
  
    rval = (LHS * dT * dT - (M - D * dT/2) * Xnm1  + (2 *M - C * dT * dT) * Xn  )/(M + D * dT/2) 
    
    lv = M* (rval - 2 * Xn + Xnm1)/(dT * dT) + D* (rval - Xnm1)/(2*dT) + C * Xn
    
#    print("check %f = %f" % (LHS,lv))
          
    return  rval

def getLHSval(Zddval, Ms, Vs, Cs, X0s):
# Cs * X0 =spring force
    return - Ms * Zddval + Cs * X0s

def zRoad(coeffs, v, Y, period, maxfreq):
    
    zR =0
   
    if maxfreq >= 0.5:
       zR = coeffs[0]* Zbaseddot('cos', period, 0.5, Y, v) + zR
       zR = coeffs[1]* Zbaseddot('sin', period, 0.5, Y, v) + zR

    if maxfreq >= 1.0:
       zR = coeffs[2]* Zbaseddot('cos', period, 1.0, Y, v) + zR
       zR = coeffs[3]* Zbaseddot('sin', period, 1.0, Y, v) + zR
    
    if maxfreq >=2.0:
       zR = coeffs[4]* Zbaseddot('cos', period, 2.0, Y, v) + zR
       zR = coeffs[5]* Zbaseddot('sin', period, 2.0, Y, v) + zR
       
    if maxfreq >=4.0:
       zR = coeffs[6]* Zbaseddot('cos', period, 4.0, Y, v) + zR
       zR = coeffs[7]* Zbaseddot('sin', period, 4.0, Y, v) + zR
    
    return zR

def  getRandomCoeffs(N):
    
     ampChoice=[0.01, 0.02, 0.025, 0.03, 0.035]
     coeffs=[]

     for i in range(0,N):
          rAmpl1=rn.choice(ampChoice) 
#          rAmpl1=rAmpl
          coeffs.append(rAmpl1)
          
     return coeffs
 
 

def  compute_sim(M, D0, V, C, X0, delT, period, maxfreq, coeffs, topsample):
    
    Y=0
# start with spring at rest
    Xnp1=X0
    Xn=X0
    Xnm1=X0


    springPos=[]
    timeVal=[]
    roadSurf=[]
    
     
    for i in range(0, topsample):
    
        t= i * delT
        timeVal.append(t)
#        print("                T=%8.2f" % t)
    
        Y= V * t  
    
        Zddval= zRoad(coeffs, V, Y, period, maxfreq)
    
#        print("Zddval %f" % Zddval)
    
# LHS= -M (ddot (Z(Y))) + CX0
        LHS= getLHSval(Zddval, M, V, C, X0)
        roadSurf.append(LHS)
    
        Xnp1 = getXnp1(LHS, M, D0, C, Xn, Xnm1, delT)
        springPos.append(Xnp1)
    
#        print("Xnp1 %8.3f  Xn %8.3f Xnm1 %8.3f" % (Xnp1, Xn, Xnm1))
    
        Xnm1=Xn
        Xn=Xnp1
        
    return [roadSurf, timeVal, springPos, t]

def add_sample(M, D0, V, C, X0, delT, period, maxfreq, botsample, topsample, lval,Ncoeffs, Rcoeffs, road_input_type):
 # compute discriminant
    disc= D0*D0 - 4 * M * C   
    
    [roadSurf, timeVals, springPos, tmax]= compute_sim(M, D0, V, C, X0, delT, period, maxfreq, Rcoeffs, topsample)

    yval=[]
    Xdat=[]

#    print("sample D0=%d label=%s" % (D0,lval )) 
#    print("D=%12.2f disc  %12.2f   maxfreq= %f" % (D0, disc,   maxfreq))
#    if disc < 0:
#        print("sqrt = %f" % math.sqrt(-disc))
 
# assume botsample is > 3

    if road_input_type=='vibration':
        tupleLen=8
    elif road_input_type=='surface':
        tupleLen=2
    else:
        print("unknown road_type %s" % road_type)
        tupleLen=2
 
# in this case include roadSurf = LHS as variable
    xnorm=10000 
    for i in range(botsample,topsample):
        if tupleLen==2:
# road input
           Xdat.append([roadSurf[i]/xnorm, springPos[i-2], springPos[i-1], springPos[i]])
# in vehicle vibration
        elif tupleLen==5:
           Xdat.append([springPos[i-5], springPos[i-4], springPos[i-3], springPos[i-2], springPos[i-1], springPos[i]])
#  in vehicle vibration (long)
        elif tupleLen==8:
           Xdat.append([springPos[-8], springPos[-7], springPos[-6], springPos[i-5], springPos[i-4], springPos[i-3], springPos[i-2], springPos[i-1], springPos[i]])
        else:
            print("Unsupported tupleLen %d" % tupleLen)
            return [[],[]]
        
        yval.append(lval)
 
    return [Xdat, yval]
    

# mass    
M=2000 
#   5cm compression
X0= 0.05
# spring const    

C= 0.6  * 10e+04
delT=0.25
# interesting values 500, 5000, 15000, 25000
 
# damping
Dvalues=[5000, 5500, 6000, 6500, 4500, 4000, 3500, 500, 600, 700, 800, 400, 300, 200]

LABELvalues=['good','good', 'good', 'good', 'good','good','good','bad','bad','bad','bad','bad','bad','bad']

dindexlist=[x for x in range(0,14)]

 
# car moves at 16.66 m/s
V= 16.66 
period= 16.66 
maxfreq=4.0
 
botsample=400 
topsample=500
Ncoeffs=8

X=[]
y=[]
ngood=0
nbad=0

nruns=500
testfraction=0.3
experiment_type='random_roads'
#experiment_type='standard_road'

# initialize road
Rcoeffs=getRandomCoeffs(Ncoeffs) 

ldindexlist=[x for x in range(0, 100* nruns)]

for i in range(0,nruns):
    
           dindex=rn.choice(dindexlist)

           D0=Dvalues[dindex]
           labval=LABELvalues[dindex]
    
 
           if experiment_type=='random_roads':
              Rcoeffs=getRandomCoeffs(Ncoeffs)
              

 
#  For  in vehicle vibration road_input_type='vibration'
#  For  road input set road_input_type='surface'
           
           road_input_type='surface'
 
           [Xdat, yval]= add_sample(M, D0, V, C, X0, delT, period, maxfreq, botsample, topsample, labval,Ncoeffs, Rcoeffs, road_input_type)
           
# [roadsurf, Xn-2, Xn-1, Xn]
           if yval[0]=='good':
               ngood+=1
           if yval[0]=='bad':
               nbad+=1
 
           for j in range(0, len(Xdat)):
                X.append(Xdat[j])
                y.append(yval[j])
                

print("shuffling %d entries" % len(ldindexlist))
rn.shuffle(ldindexlist)
# sanity check
print(ldindexlist[0:10])

X_rn=[]
y_rn=[]

for i in range(0, len(X)):
    X_rn.append(X[ldindexlist[i]])
    y_rn.append(y[ldindexlist[i]])
    
    
           
print("made %d samples with botsample %d topsample %d" % (nruns,botsample, topsample))
print("maxfreq= %8.2f M= %8.2f V=%8.2f C=%8.2f" % (maxfreq, M, V, C))

totalN=len(X)
print("Total samples %d good runs %d bad runs %d" % (totalN, ngood, nbad))

#print(Xdat)

print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))
 




 


 

 
    
    
    



shuffling 50000 entries
[22424, 23263, 24069, 22766, 10163, 29433, 25754, 24058, 28799, 9486]
made 500 samples with botsample 400 topsample 500
maxfreq=     4.00 M=  2000.00 V=   16.66 C=60000.00
Total samples 50000 good runs 254 bad runs 246
2021-05-21 01:54:40


The confusion matrix is a common metric to measure the performance of a classification algorithm. In this case, only "good" and "bad" are labelled (binary). So the confusion matrix can be shown as below:

|               | Predicted(No) | Predicted(Yes)  |
| ------------- |:---------------:| -----------------:|
| **Actual(No)**   | True Negatives (TN) | False Positives (FP) |
| **Actual(Yes)**  | False Negatives (FN) | True Positives (TP) |

From the matrix, we could get the Accuracy by this formula:
$$ Accuracy = \frac {TP + TN}{TP + TN + FP + FN} $$

And the Error rate would be $1-Accuracy$, same as
$$ ErrorRate = \frac {FP + FN}{TP + TN + FP + FN} $$

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
def ml_result_report(y_test, y_pred):
  # Create Confusion Matrix with testing and prediction data
  Mc = metrics.confusion_matrix(y_test, y_pred)

  totalN = Mc[0][0] + Mc[0][1] + Mc[1][0] + Mc[1][1]
  misclassifiedN = Mc[0][1] + Mc[1][0]

  errorRate = misclassifiedN / totalN

  print("confusion matrix: on test data set")
  print(Mc)

  print("errorRate %5.3f" % errorRate)
  print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))
  print("N=%d : experiment_type: %s  road_input_type: %s" % (nruns,experiment_type, road_input_type))

In [2]:
# Split samples
X_train, X_test, y_train, y_test = train_test_split(X_rn, y_rn, test_size=testfraction, random_state=42)

In [3]:
print(len(X_train), len(y_train))


37500 37500


In [4]:
# Standardization of sample
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[-1.34739599, -0.56561797, -1.33855545, -0.74212603],
       [ 1.62015677,  0.2460635 ,  1.87908785,  1.39094046],
       [ 0.37701005,  1.72934617,  1.19623471, -0.49227254],
       ...,
       [-1.08646433, -1.68841625, -1.24535057,  0.50715179],
       [-0.92912275, -0.17204074, -1.099883  , -0.76859575],
       [ 0.81094154, -1.54774079, -0.5299586 ,  1.11947538]])

In [5]:
# KNN
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [6]:
knn.score(X_test_scaled, y_test)

0.97968

In [7]:
knn.score(X_train_scaled, y_train)

0.9902933333333334

In [8]:
y_pred_knn = knn.predict(X_test_scaled)

In [9]:
# Confusion Matrix for KNN
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_knn)

array([[6157,   41],
       [ 213, 6089]])

In [ ]:
# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rf.score(X_test_scaled, y_test)

0.97496

In [ ]:
knn.score(X_train_scaled, y_train)

0.9918133333333333

# Neural Network

In [2]:
# Confirm the unique label values
unique = list(dict.fromkeys(y_rn))
unique

['bad', 'good']

In [3]:

X_train, X_test, y_train, y_test = train_test_split(X_rn, y_rn, random_state=42)



In [4]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[-0.13007432,  1.46143808,  0.04876827, -1.5330586 ],
       [ 0.91091633, -0.80203482,  1.10820151,  1.63064832],
       [-0.83662889,  0.40935125, -0.78275212, -1.1748913 ],
       ...,
       [-0.87717078, -0.17245449, -0.80578299, -0.59081935],
       [ 0.95475532, -0.24396082,  0.86302739,  0.93560387],
       [-1.61655609,  0.58041581, -1.53757117, -2.06746903]])

In [5]:
# Transform y values
label_model = LabelEncoder()
label_model.fit(y_train)

y_train_encoded = label_model.transform(y_train)
y_test_encoded = label_model.transform(y_test)
y_train_encoded

array([0, 0, 0, ..., 1, 1, 0])

In [6]:
# Convert to categorical data


y_train_categorical = to_categorical(y_train_encoded)
y_test_categorical = to_categorical(y_test_encoded)
y_train_categorical

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [7]:
# Building NN model

model = Sequential()
model.add(Dense(units=4, activation="relu", input_dim=4))
model.add(Dense(units=3, activation="softmax"))
model.add(Dense(units=3, activation="relu"))
model.add(Dense(units=2, activation="softmax"))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=["accuracy"])
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 8         
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


In [8]:
# Fitting model
model.fit(X_train_scaled, y_train_categorical, epochs=200, shuffle=True, verbose=2)

Epoch 1/200
1172/1172 - 2s - loss: 0.6766 - accuracy: 0.5744
Epoch 2/200
1172/1172 - 1s - loss: 0.4677 - accuracy: 0.8326
Epoch 3/200
1172/1172 - 1s - loss: 0.3024 - accuracy: 0.8956
Epoch 4/200
1172/1172 - 1s - loss: 0.2655 - accuracy: 0.9034
Epoch 5/200
1172/1172 - 1s - loss: 0.2525 - accuracy: 0.9054
Epoch 6/200
1172/1172 - 1s - loss: 0.2456 - accuracy: 0.9062
Epoch 7/200
1172/1172 - 1s - loss: 0.2411 - accuracy: 0.9067
Epoch 8/200
1172/1172 - 1s - loss: 0.2376 - accuracy: 0.9075
Epoch 9/200
1172/1172 - 1s - loss: 0.2350 - accuracy: 0.9072
Epoch 10/200
1172/1172 - 1s - loss: 0.2324 - accuracy: 0.9088
Epoch 11/200
1172/1172 - 1s - loss: 0.2302 - accuracy: 0.9097
Epoch 12/200
1172/1172 - 1s - loss: 0.2283 - accuracy: 0.9106
Epoch 13/200
1172/1172 - 1s - loss: 0.2261 - accuracy: 0.9109
Epoch 14/200
1172/1172 - 1s - loss: 0.2242 - accuracy: 0.9109
Epoch 15/200
1172/1172 - 1s - loss: 0.2233 - accuracy: 0.9116
Epoch 16/200
1172/1172 - 1s - loss: 0.2216 - accuracy: 0.9119
Epoch 17/200
1172

In [9]:
# Evaluate the model
model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

391/391 - 0s - loss: 0.1747 - accuracy: 0.9371


[0.1746901422739029, 0.9371200203895569]

In [10]:
y_pred = model.predict(X_test_scaled)
y_pred

array([[3.1878762e-02, 9.6812123e-01],
       [9.9986744e-01, 1.3251600e-04],
       [9.9992764e-01, 7.2340452e-05],
       ...,
       [9.9997902e-01, 2.0987820e-05],
       [9.5381355e-01, 4.6186473e-02],
       [9.9999142e-01, 8.5676775e-06]], dtype=float32)

In [11]:
confusion_matrix(y_test_categorical.argmax(axis=1), y_pred.argmax(axis=1))

array([[5526,  590],
       [ 196, 6188]])

In [ ]:
# INSERT ML algorithm here (X_rn, y_rn) train vs test sets


#Mc=metrics.confusion_matrix(y_rn[int(testfraction*totalN):], y_pred)

#totalN=Mc[0][0] + Mc[0][1] + Mc[1][0] + Mc[1][1]
#misclassifiedN = Mc[0][1] + Mc[1][0]

#errorRate= misclassifiedN / totalN

#print("confusion matrix: on test data set")
#print(Mc)

#print("errorRate %5.3f" % errorRate)
print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))
print("N=%d : experiment_type: %s  road_input_type: %s" % (nruns,experiment_type, road_input_type))